### ISSUE TITLE
Responsiveness of input is delayed

### ISSUE THREAD

**Issue by DaVince** [ShadauxCat/CATSFC#22] opened 2011-07-29 16:46 UTC
I just switched from NDSSFC to CATSFC, and found that the button and screen input are delayed a bit more than they were in NDSSFC. It feels like the response time is delayed by at least a hundredth of a second more than on the official emulator.

Not only that, the touch screen input is ignored if you tap it too quickly. On NDSSFC, the menu will pop up immediately.

EDIT: I find that the delay occasionally makes the buttons "double press" or not press at all during gameplay. This makes it more difficult to navigate through game menus and such.

This might have something to do with decreased performance of the emulator in general - Hourai High (with hardpatched translation) now frameskips much more than before, even on CPU frequency 5.

**Comment by Nebuleon** [comment] 2012-12-28 20:49
This has been much improved in commit a0d0c5e7a5bdc396b4c370a750273b6e3b963bb0 (2012-12-21).

Sound synchronisation can still delay button press recognition as of commit c01a2a42168695233ecc69c4a60ed918e7701fb9 (2012-12-28). As a workaround, you can disable sound, and all button presses will be recognised without fault.

**Comment by Nebuleon** [comment] 2013-01-09 00:58
Definitively fixed in CATSFC 1.16.

**Closed as completed by Nebuleon** 2013-01-09 00:58 UTC
Labels: Missing information

**Comment by Nebuleon** [comment] 2013-02-04 20:11
This was unfixed in CATSFC 1.18, and refixed in CATSFC 1.28 (compiling with the most recent SDK).

**Comment by HitsuMaruku** [comment] 2013-02-06 01:25
The previous problems I had with lost input or over-sensitivity is gone completely. As far as I can tell, the issue is resolved completely.

Out of curiosity, does compiling with a more recent version of the SDK make a noticeable difference? Is is simply execution efficiency, or are there fundamental changes that necessitate the upgrade?

**Comment by Nebuleon** [comment] 2013-02-06 03:14
It was a "downgrade" apparently, because BassAceGold stated on GBAtemp that 1.2 (which I compiled with for CATSFC 1.28) is really 0.12, earlier than 0.13 beta, but 0.13 is a beta that messed up the communication protocol/timings, maybe. And there's the fact that NOT skipping frames causes congestion on the cart-to-DS bus, so it can't emit requests for controls while it's busy rapidly sending screens and audio.

**Comment by HitsuMaruku** [comment] 2013-02-06 15:11
Makes a lot of sense. Nice catch! I wouldn't have thought to look at the compiler for issues.
